### ISSUE TITLE
Application Commands Part 5: Migration

### ISSUE THREAD

**Issue by diewellenlaenge** [NullDev/CSZ-Bot#119]
## Bedingungen

- Bitte zu erst die Application Commands Übersicht lesen (#114)
- Geblockt von Statuful Commands #118 (das muss zu erst erledigt werden)

## Beschreibung

Da die Grundlagen nun vorhanden sind, können wir alle Module migrieren. Es ist unnötig, für jedes Modul ein eigenes Issue zu erstellen. Stattdessen sollte jedes Modul einen eigenen PR kriegen. Jede Menge Potential fürs Hacktoberfest :)

## Todos
- [ ] Es muss eine Lösung oder Entscheidung für oder gegen „variadic arguments“ getroffen werden
- [ ] Wir müssen eine Entscheidung treffen wie das Zusammenspiel der Permissions von Slash-Commands und MessageCommands laufen soll (Vorschlag von @tobi6112: Commands definieren ihre Permissions)

- Normale Commands
  - [ ] Erleuchtung
  - [ ] Extend (siehe hier: #120)
  - [ ] Ficktabelle
  - [x] Info
  - [ ] Invite
  - [ ] Metafrage
  - [ ] Min
  - [ ] Mock
  - [ ] Never
  - [ ] Poll (sehr komplex, bitte hier schauen: #120)
  - [ ] Roll
  - [x] SDM
  - [ ] Selfban
  - [ ] Woisping
  - [ ] Vote (siehe hier: #120)
- Modcommands
  - [ ] Assigner
  - [x] Ban (am besten mit `unban` vereinen in eine Datei)
  - [ ] Listroles
  - [x] Stempeln
- [ ] Hilfe am Ende komplett refactoren, sodass nur noch eine Liste aller Commands angezeigt wird. Die einzelnen Infos bietet Discord direkt per Hilfe an.

## Beispiele

Aus dem Fork:

- [Normale Commands](https://github.com/NullDev/CSC-Bot/tree/slash-commands-ts/src/commands)
- [Modcommands](https://github.com/NullDev/CSC-Bot/tree/slash-commands-ts/src/commands/modcommands)

**Comment by diewellenlaenge** [comment]
Bin auch dafür, dass die Commands ihre Permissions selber definieren über den Builder.

Man müsste mal recherchieren, ob man den Permissions auch vertrauen kann oder ob es möglich ist, das zu umgehen.
Habe ich mich bei Parametern auch schon gefragt. Ob man quasi doch irgendwie nen String absenden kann, obwohl man ein Integer erwartet.

**Comment by tobi6112** [comment]
Habe einige Commands jetzt migriert, fühlt sich noch falsch an. Der InteractionHandler ist repetitiv und müsste mehr arbeit abnehmen.
